spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/patentnew?useSSL=false
    username: cbm7119
    password: Sofkdsn001!
#  boot:
#    admin:
#      client:
#        url: localhost:1111/
#        period: 5000
#        connect-timeout: 1000

# management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: ALWAYS

server:
  port: 0
---
spring:
  profiles: dev
---
spring:
  profiles: prod